config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :videos
  resources :libraries
  resources :audios
  resources :historicals
  resources :documents
  resources :books
  devise_for :users
  get 'welcome/index'
mount Judge::Engine => '/judge'

   root 'welcome#index'

end

app/models/library.rb
class Library < ActiveRecord::Base
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:titulo, :subtitulo, :autor, :colaborador, :clasificacion, :editorial, :edicion, :edicion, :serie, :traduccion, :bibliografia, :indice, :apendice, :apendice, :isbn, :contenido, :cantidad, :acervo, :ano_publicacion, :anaquel, :peldano)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br>
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :colaborador %><br>
    <%= f.text_field :colaborador %>
  </div>
  <div class="field">
    <%= f.label :clasificacion %><br>
    <%= f.text_field :clasificacion %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br>
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :edicion %><br>
    <%= f.text_field :edicion %>
  </div>
  <div class="field">
    <%= f.label :edicion %><br>
    <%= f.text_field :edicion %>
  </div>
  <div class="field">
    <%= f.label :serie %><br>
    <%= f.text_field :serie %>
  </div>
  <div class="field">
    <%= f.label :traduccion %><br>
    <%= f.text_field :traduccion %>
  </div>
  <div class="field">
    <%= f.label :bibliografia %><br>
    <%= f.text_field :bibliografia %>
  </div>
  <div class="field">
    <%= f.label :indice %><br>
    <%= f.text_field :indice %>
  </div>
  <div class="field">
    <%= f.label :apendice %><br>
    <%= f.text_field :apendice %>
  </div>
  <div class="field">
    <%= f.label :apendice %><br>
    <%= f.text_field :apendice %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_field :contenido %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :acervo %><br>
    <%= f.text_field :acervo %>
  </div>
  <div class="field">
    <%= f.label :ano_publicacion %><br>
    <%= f.text_field :ano_publicacion %>
  </div>
  <div class="field">
    <%= f.label :anaquel %><br>
    <%= f.text_field :anaquel %>
  </div>
  <div class="field">
    <%= f.label :peldano %><br>
    <%= f.text_field :peldano %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Subtitulo</th>
      <th>Autor</th>
      <th>Colaborador</th>
      <th>Clasificacion</th>
      <th>Editorial</th>
      <th>Edicion</th>
      <th>Edicion</th>
      <th>Serie</th>
      <th>Traduccion</th>
      <th>Bibliografia</th>
      <th>Indice</th>
      <th>Apendice</th>
      <th>Apendice</th>
      <th>Isbn</th>
      <th>Contenido</th>
      <th>Cantidad</th>
      <th>Acervo</th>
      <th>Ano publicacion</th>
      <th>Anaquel</th>
      <th>Peldano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.titulo %></td>
        <td><%= library.subtitulo %></td>
        <td><%= library.autor %></td>
        <td><%= library.colaborador %></td>
        <td><%= library.clasificacion %></td>
        <td><%= library.editorial %></td>
        <td><%= library.edicion %></td>
        <td><%= library.edicion %></td>
        <td><%= library.serie %></td>
        <td><%= library.traduccion %></td>
        <td><%= library.bibliografia %></td>
        <td><%= library.indice %></td>
        <td><%= library.apendice %></td>
        <td><%= library.apendice %></td>
        <td><%= library.isbn %></td>
        <td><%= library.contenido %></td>
        <td><%= library.cantidad %></td>
        <td><%= library.acervo %></td>
        <td><%= library.ano_publicacion %></td>
        <td><%= library.anaquel %></td>
        <td><%= library.peldano %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @library.titulo %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @library.subtitulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @library.autor %>
</p>

<p>
  <strong>Colaborador:</strong>
  <%= @library.colaborador %>
</p>

<p>
  <strong>Clasificacion:</strong>
  <%= @library.clasificacion %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @library.editorial %>
</p>

<p>
  <strong>Edicion:</strong>
  <%= @library.edicion %>
</p>

<p>
  <strong>Edicion:</strong>
  <%= @library.edicion %>
</p>

<p>
  <strong>Serie:</strong>
  <%= @library.serie %>
</p>

<p>
  <strong>Traduccion:</strong>
  <%= @library.traduccion %>
</p>

<p>
  <strong>Bibliografia:</strong>
  <%= @library.bibliografia %>
</p>

<p>
  <strong>Indice:</strong>
  <%= @library.indice %>
</p>

<p>
  <strong>Apendice:</strong>
  <%= @library.apendice %>
</p>

<p>
  <strong>Apendice:</strong>
  <%= @library.apendice %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @library.isbn %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @library.contenido %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @library.cantidad %>
</p>

<p>
  <strong>Acervo:</strong>
  <%= @library.acervo %>
</p>

<p>
  <strong>Ano publicacion:</strong>
  <%= @library.ano_publicacion %>
</p>

<p>
  <strong>Anaquel:</strong>
  <%= @library.anaquel %>
</p>

<p>
  <strong>Peldano:</strong>
  <%= @library.peldano %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>