config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :videos
  resources :libraries
  resources :audios
  resources :historicals
  resources :documents
  resources :books
  devise_for :users
  get 'welcome/index'
mount Judge::Engine => '/judge'

   root 'welcome#index'

end

app/models/historical.rb
class Historical < ActiveRecord::Base
end

app/controllers/historicals_controller.rb
class HistoricalsController < ApplicationController
  before_action :set_historical, only: [:show, :edit, :update, :destroy]

  # GET /historicals
  # GET /historicals.json
  def index
    @historicals = Historical.all
  end

  # GET /historicals/1
  # GET /historicals/1.json
  def show
  end

  # GET /historicals/new
  def new
    @historical = Historical.new
  end

  # GET /historicals/1/edit
  def edit
  end

  # POST /historicals
  # POST /historicals.json
  def create
    @historical = Historical.new(historical_params)

    respond_to do |format|
      if @historical.save
        format.html { redirect_to @historical, notice: 'Historical was successfully created.' }
        format.json { render :show, status: :created, location: @historical }
      else
        format.html { render :new }
        format.json { render json: @historical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historicals/1
  # PATCH/PUT /historicals/1.json
  def update
    respond_to do |format|
      if @historical.update(historical_params)
        format.html { redirect_to @historical, notice: 'Historical was successfully updated.' }
        format.json { render :show, status: :ok, location: @historical }
      else
        format.html { render :edit }
        format.json { render json: @historical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historicals/1
  # DELETE /historicals/1.json
  def destroy
    @historical.destroy
    respond_to do |format|
      format.html { redirect_to historicals_url, notice: 'Historical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historical
      @historical = Historical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historical_params
      params.require(:historical).permit(:titulo, :subtitulo, :autor, :colaborador, :clasificacion, :editorial, :edicion, :edicion, :serie, :traduccion, :bibliografia, :indice, :apendice, :apendice, :isbn, :contenido, :cantidad, :acervo, :ano_publicacion, :anaquel, :peldano)
    end
end

app/helpers/historicals_helper.rb
module HistoricalsHelper
end

app/views/historicals/_form.html.erb
<%= form_for(@historical) do |f| %>
  <% if @historical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@historical.errors.count, "error") %> prohibited this historical from being saved:</h2>

      <ul>
      <% @historical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br>
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :colaborador %><br>
    <%= f.text_field :colaborador %>
  </div>
  <div class="field">
    <%= f.label :clasificacion %><br>
    <%= f.text_field :clasificacion %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br>
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :edicion %><br>
    <%= f.text_field :edicion %>
  </div>
  <div class="field">
    <%= f.label :edicion %><br>
    <%= f.text_field :edicion %>
  </div>
  <div class="field">
    <%= f.label :serie %><br>
    <%= f.text_field :serie %>
  </div>
  <div class="field">
    <%= f.label :traduccion %><br>
    <%= f.text_field :traduccion %>
  </div>
  <div class="field">
    <%= f.label :bibliografia %><br>
    <%= f.text_field :bibliografia %>
  </div>
  <div class="field">
    <%= f.label :indice %><br>
    <%= f.text_field :indice %>
  </div>
  <div class="field">
    <%= f.label :apendice %><br>
    <%= f.text_field :apendice %>
  </div>
  <div class="field">
    <%= f.label :apendice %><br>
    <%= f.text_field :apendice %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_field :contenido %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :acervo %><br>
    <%= f.text_field :acervo %>
  </div>
  <div class="field">
    <%= f.label :ano_publicacion %><br>
    <%= f.text_field :ano_publicacion %>
  </div>
  <div class="field">
    <%= f.label :anaquel %><br>
    <%= f.text_field :anaquel %>
  </div>
  <div class="field">
    <%= f.label :peldano %><br>
    <%= f.text_field :peldano %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/historicals/edit.html.erb
<h1>Editing Historical</h1>

<%= render 'form' %>

<%= link_to 'Show', @historical %> |
<%= link_to 'Back', historicals_path %>

app/views/historicals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Historicals</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Subtitulo</th>
      <th>Autor</th>
      <th>Colaborador</th>
      <th>Clasificacion</th>
      <th>Editorial</th>
      <th>Edicion</th>
      <th>Edicion</th>
      <th>Serie</th>
      <th>Traduccion</th>
      <th>Bibliografia</th>
      <th>Indice</th>
      <th>Apendice</th>
      <th>Apendice</th>
      <th>Isbn</th>
      <th>Contenido</th>
      <th>Cantidad</th>
      <th>Acervo</th>
      <th>Ano publicacion</th>
      <th>Anaquel</th>
      <th>Peldano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historicals.each do |historical| %>
      <tr>
        <td><%= historical.titulo %></td>
        <td><%= historical.subtitulo %></td>
        <td><%= historical.autor %></td>
        <td><%= historical.colaborador %></td>
        <td><%= historical.clasificacion %></td>
        <td><%= historical.editorial %></td>
        <td><%= historical.edicion %></td>
        <td><%= historical.edicion %></td>
        <td><%= historical.serie %></td>
        <td><%= historical.traduccion %></td>
        <td><%= historical.bibliografia %></td>
        <td><%= historical.indice %></td>
        <td><%= historical.apendice %></td>
        <td><%= historical.apendice %></td>
        <td><%= historical.isbn %></td>
        <td><%= historical.contenido %></td>
        <td><%= historical.cantidad %></td>
        <td><%= historical.acervo %></td>
        <td><%= historical.ano_publicacion %></td>
        <td><%= historical.anaquel %></td>
        <td><%= historical.peldano %></td>
        <td><%= link_to 'Show', historical %></td>
        <td><%= link_to 'Edit', edit_historical_path(historical) %></td>
        <td><%= link_to 'Destroy', historical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historical', new_historical_path %>

app/views/historicals/new.html.erb
<h1>New Historical</h1>

<%= render 'form' %>

<%= link_to 'Back', historicals_path %>

app/views/historicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @historical.titulo %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @historical.subtitulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @historical.autor %>
</p>

<p>
  <strong>Colaborador:</strong>
  <%= @historical.colaborador %>
</p>

<p>
  <strong>Clasificacion:</strong>
  <%= @historical.clasificacion %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @historical.editorial %>
</p>

<p>
  <strong>Edicion:</strong>
  <%= @historical.edicion %>
</p>

<p>
  <strong>Edicion:</strong>
  <%= @historical.edicion %>
</p>

<p>
  <strong>Serie:</strong>
  <%= @historical.serie %>
</p>

<p>
  <strong>Traduccion:</strong>
  <%= @historical.traduccion %>
</p>

<p>
  <strong>Bibliografia:</strong>
  <%= @historical.bibliografia %>
</p>

<p>
  <strong>Indice:</strong>
  <%= @historical.indice %>
</p>

<p>
  <strong>Apendice:</strong>
  <%= @historical.apendice %>
</p>

<p>
  <strong>Apendice:</strong>
  <%= @historical.apendice %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @historical.isbn %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @historical.contenido %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @historical.cantidad %>
</p>

<p>
  <strong>Acervo:</strong>
  <%= @historical.acervo %>
</p>

<p>
  <strong>Ano publicacion:</strong>
  <%= @historical.ano_publicacion %>
</p>

<p>
  <strong>Anaquel:</strong>
  <%= @historical.anaquel %>
</p>

<p>
  <strong>Peldano:</strong>
  <%= @historical.peldano %>
</p>

<%= link_to 'Edit', edit_historical_path(@historical) %> |
<%= link_to 'Back', historicals_path %>